[2024-06-14T01:27:44.134+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T01:27:44.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:27:34.783392+00:00 [queued]>
[2024-06-14T01:27:44.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:27:34.783392+00:00 [queued]>
[2024-06-14T01:27:44.150+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T01:27:44.164+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-14 01:27:34.783392+00:00
[2024-06-14T01:27:44.169+0000] {standard_task_runner.py:63} INFO - Started process 152313 to run task
[2024-06-14T01:27:44.173+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-14T01:27:34.783392+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpex4if237']
[2024-06-14T01:27:44.174+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask tsk_is_file_in_s3_available
[2024-06-14T01:27:44.209+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:27:34.783392+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T01:27:44.287+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T01:27:34.783392+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T01:27:34.783392+00:00'
[2024-06-14T01:27:44.287+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T01:27:44.300+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-14T01:27:44.300+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:27:44.305+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-14T01:27:44.306+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T01:27:49.708+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:27:54.717+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:27:59.726+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:04.735+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:09.747+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:14.760+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:19.768+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:24.780+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:29.791+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:34.812+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:39.825+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:44.833+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:49.842+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:54.854+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:28:59.863+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:04.871+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:09.881+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:14.892+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:19.901+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:24.910+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:29.918+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:34.927+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:39.935+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:44.944+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012737.csv
[2024-06-14T01:29:44.953+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T01:29:44.953+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.65267329802737 seconds exceeds the specified timeout of 120.0.
[2024-06-14T01:29:44.957+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-14T01:27:34.783392+00:00, execution_date=20240614T012734, start_date=20240614T012744, end_date=20240614T012944
[2024-06-14T01:29:44.969+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 120.65267329802737 seconds exceeds the specified timeout of 120.0.; 152313)
[2024-06-14T01:29:45.005+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T01:29:45.014+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T01:29:45.015+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
