[2024-06-14T01:06:53.457+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T01:06:53.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T01:06:53.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T01:06:53.473+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T01:06:53.488+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-13 00:00:00+00:00
[2024-06-14T01:06:53.494+0000] {standard_task_runner.py:63} INFO - Started process 150834 to run task
[2024-06-14T01:06:53.498+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpoqhbpa9x']
[2024-06-14T01:06:53.499+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask tsk_is_file_in_s3_available
[2024-06-14T01:06:53.537+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-06-13T00:00:00+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T01:06:53.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T01:06:53.616+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T01:06:53.628+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-14T01:06:53.629+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:06:53.634+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-14T01:06:53.634+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T01:06:59.049+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:04.061+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:09.071+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:14.083+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:19.098+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:24.107+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:29.116+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:34.125+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:39.135+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:44.148+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:49.161+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:54.169+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:07:59.182+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:04.192+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:09.203+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:14.217+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:19.226+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:24.236+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:29.245+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:34.256+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:39.264+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:44.273+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:49.284+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:54.293+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024010646.csv
[2024-06-14T01:08:54.305+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T01:08:54.306+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.67666891904082 seconds exceeds the specified timeout of 120.0.
[2024-06-14T01:08:54.310+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T010653, end_date=20240614T010854
[2024-06-14T01:08:54.322+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 107 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 120.67666891904082 seconds exceeds the specified timeout of 120.0.; 150834)
[2024-06-14T01:08:54.354+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T01:08:54.363+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T01:08:54.364+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
