[2024-06-14T02:59:07.842+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T02:59:07.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T02:57:51.823133+00:00 [queued]>
[2024-06-14T02:59:07.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T02:57:51.823133+00:00 [queued]>
[2024-06-14T02:59:07.859+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T02:59:07.874+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-14 02:57:51.823133+00:00
[2024-06-14T02:59:07.878+0000] {standard_task_runner.py:63} INFO - Started process 158941 to run task
[2024-06-14T02:59:07.881+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-14T02:57:51.823133+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpsp32t9rg']
[2024-06-14T02:59:07.883+0000] {standard_task_runner.py:91} INFO - Job 177: Subtask tsk_is_file_in_s3_available
[2024-06-14T02:59:07.918+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T02:57:51.823133+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T02:59:07.996+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T02:57:51.823133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T02:57:51.823133+00:00'
[2024-06-14T02:59:07.997+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T02:59:08.010+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-14T02:59:08.010+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/response_data_14062024025854.csv
[2024-06-14T02:59:08.015+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-14T02:59:08.016+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T02:59:08.424+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-14T02:59:08.425+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T02:59:08.429+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-14T02:57:51.823133+00:00, execution_date=20240614T025751, start_date=20240614T025907, end_date=20240614T025908
[2024-06-14T02:59:08.455+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-14T02:59:08.466+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T02:59:08.467+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
