[2024-06-14T01:20:07.722+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T01:20:07.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:19:58.660581+00:00 [queued]>
[2024-06-14T01:20:07.738+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:19:58.660581+00:00 [queued]>
[2024-06-14T01:20:07.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T01:20:07.754+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-14 01:19:58.660581+00:00
[2024-06-14T01:20:07.759+0000] {standard_task_runner.py:63} INFO - Started process 151869 to run task
[2024-06-14T01:20:07.762+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-14T01:19:58.660581+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmptoz99kl4']
[2024-06-14T01:20:07.764+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask tsk_is_file_in_s3_available
[2024-06-14T01:20:07.803+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:19:58.660581+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T01:20:07.884+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T01:19:58.660581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T01:19:58.660581+00:00'
[2024-06-14T01:20:07.884+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T01:20:07.897+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-14T01:20:07.898+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:07.903+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-14T01:20:07.904+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T01:20:13.384+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:18.395+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:23.406+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:28.415+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:33.425+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:38.437+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:43.447+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:48.456+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:53.466+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:20:58.477+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:03.487+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:08.497+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:13.507+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:18.517+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:23.527+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:28.537+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:33.547+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:38.557+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:43.568+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:48.578+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:53.588+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:21:58.598+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:22:03.608+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:22:08.620+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024012000.csv
[2024-06-14T01:22:08.630+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T01:22:08.630+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.7323538439814 seconds exceeds the specified timeout of 120.0.
[2024-06-14T01:22:08.635+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-14T01:19:58.660581+00:00, execution_date=20240614T011958, start_date=20240614T012007, end_date=20240614T012208
[2024-06-14T01:22:08.647+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 116 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 120.7323538439814 seconds exceeds the specified timeout of 120.0.; 151869)
[2024-06-14T01:22:08.695+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T01:22:08.704+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T01:22:08.705+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
