[2024-06-14T01:34:47.920+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T01:34:47.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:34:38.621004+00:00 [queued]>
[2024-06-14T01:34:47.936+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:34:38.621004+00:00 [queued]>
[2024-06-14T01:34:47.936+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-14T01:34:47.952+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-14 01:34:38.621004+00:00
[2024-06-14T01:34:47.957+0000] {standard_task_runner.py:63} INFO - Started process 152689 to run task
[2024-06-14T01:34:47.960+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-14T01:34:38.621004+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmptpzez7sy']
[2024-06-14T01:34:47.962+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask tsk_is_file_in_s3_available
[2024-06-14T01:34:47.996+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-14T01:34:38.621004+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T01:34:48.073+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T01:34:38.621004+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T01:34:38.621004+00:00'
[2024-06-14T01:34:48.074+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T01:34:48.087+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-14T01:34:48.087+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:34:48.092+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-14T01:34:48.093+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-14T01:34:53.498+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:34:58.508+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:03.519+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:08.530+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:13.541+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:18.551+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:23.560+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:28.571+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:33.581+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:38.592+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:43.603+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:48.613+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:53.622+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:35:58.634+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:03.643+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:08.653+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:13.663+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:18.676+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:23.688+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:28.698+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:33.709+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:38.720+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:43.731+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:48.741+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/reponse_data_14062024013441.csv
[2024-06-14T01:36:48.753+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T01:36:48.753+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 183, in execute
    super().execute(context)
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 120.6656186580658 seconds exceeds the specified timeout of 120.0.
[2024-06-14T01:36:48.757+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-14T01:34:38.621004+00:00, execution_date=20240614T013438, start_date=20240614T013447, end_date=20240614T013648
[2024-06-14T01:36:48.769+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 122 for task tsk_is_file_in_s3_available (Sensor has timed out; run duration of 120.6656186580658 seconds exceeds the specified timeout of 120.0.; 152689)
[2024-06-14T01:36:48.803+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T01:36:48.812+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T01:36:48.813+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
