[2024-06-14T20:04:43.147+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T20:04:43.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-14T20:04:12.451099+00:00 [queued]>
[2024-06-14T20:04:43.169+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-14T20:04:12.451099+00:00 [queued]>
[2024-06-14T20:04:43.169+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-14T20:04:43.184+0000] {taskinstance.py:2330} INFO - Executing <Task(S3ToRedshiftOperator): tsk_transfer_s3_to_redshift> on 2024-06-14 20:04:12.451099+00:00
[2024-06-14T20:04:43.189+0000] {standard_task_runner.py:63} INFO - Started process 171165 to run task
[2024-06-14T20:04:43.194+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_transfer_s3_to_redshift', 'manual__2024-06-14T20:04:12.451099+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmp1gpdi9d5']
[2024-06-14T20:04:43.196+0000] {standard_task_runner.py:91} INFO - Job 191: Subtask tsk_transfer_s3_to_redshift
[2024-06-14T20:04:43.240+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-06-14T20:04:12.451099+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-14T20:04:43.315+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T20:04:12.451099+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T20:04:12.451099+00:00'
[2024-06-14T20:04:43.316+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T20:04:43.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T20:04:43.340+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 145, in execute
    conn = S3Hook.get_connection(conn_id=self.aws_conn_id) if self.aws_conn_id else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/endtoend_venv/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws+s3_conn` isn't defined
[2024-06-14T20:04:43.344+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=zillow_analytics_dag, task_id=tsk_transfer_s3_to_redshift, run_id=manual__2024-06-14T20:04:12.451099+00:00, execution_date=20240614T200412, start_date=20240614T200443, end_date=20240614T200443
[2024-06-14T20:04:43.357+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 191 for task tsk_transfer_s3_to_redshift (The conn_id `aws+s3_conn` isn't defined; 171165)
[2024-06-14T20:04:43.366+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T20:04:43.379+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T20:04:43.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
