[2024-06-15T02:31:19.088+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T02:31:19.098+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-15T02:30:18.500493+00:00 [queued]>
[2024-06-15T02:31:19.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-15T02:30:18.500493+00:00 [queued]>
[2024-06-15T02:31:19.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-15T02:31:19.119+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-06-15 02:30:18.500493+00:00
[2024-06-15T02:31:19.125+0000] {standard_task_runner.py:63} INFO - Started process 184910 to run task
[2024-06-15T02:31:19.128+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-06-15T02:30:18.500493+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/zillowanalytics.py', '--cfg-path', '/tmp/tmpmd2msuri']
[2024-06-15T02:31:19.129+0000] {standard_task_runner.py:91} INFO - Job 206: Subtask tsk_is_file_in_s3_available
[2024-06-15T02:31:19.165+0000] {task_command.py:426} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-06-15T02:30:18.500493+00:00 [running]> on host ip-172-31-25-20.us-east-2.compute.internal
[2024-06-15T02:31:19.245+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T02:30:18.500493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T02:30:18.500493+00:00'
[2024-06-15T02:31:19.246+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T02:31:19.258+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-06-15T02:31:19.259+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/response_data_15062024023112.csv
[2024-06-15T02:31:19.264+0000] {base.py:84} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2024-06-15T02:31:19.265+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-06-15T02:31:24.676+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/response_data_15062024023112.csv
[2024-06-15T02:31:29.687+0000] {s3.py:117} INFO - Poking for key : s3://cleaned-data-zone-csv-bucket-ng/response_data_15062024023112.csv
[2024-06-15T02:31:29.700+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-15T02:31:29.700+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T02:31:29.705+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-06-15T02:30:18.500493+00:00, execution_date=20240615T023018, start_date=20240615T023119, end_date=20240615T023129
[2024-06-15T02:31:29.753+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-15T02:31:29.772+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-15T02:31:29.778+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
